version: 2
jobs:
  build:
    working_directory: ~/circle_ci_example
    docker:
      - image: ruby:2.6.0
        environment:
          PG_HOST: localhost
          PG_USER: ubuntu
      - image: postgres:9.6
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_example_test
    steps:
      - checkout

      - restore_cache:
          keys:
            - circle_ci_example-{{ checksum "Gemfile.lock" }}
            - circle_ci_example-
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      - save_cache:
          key: circle_ci_example-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Create database config
          command: cp db/config.yml.circle_ci db/config.yml

      - run:
          name: Set up DB
          command: |
            bundle exec rake db:create db:schema:load --trace
            bundle exec rake db:migrate
          environment:
            DATABASE_URL: "postgres://ubuntu@localhost:5432/circle_example_test"

      - run:
          name: Run Tests
          command: bundle exec rspec
